In [1]:
import numpy as np

# Numpy Array

## 1D List -> Numpy Array

In [3]:
vec = [1, 2, 3]

In [5]:
np_vec = np.array(vec)

In [6]:
np_vec

array([1, 2, 3])

In [7]:
type(np_vec)

numpy.ndarray

## 2D Matrix -> Numpy Array

In [8]:
mat = [[2, 6, 8], [3, 7, 0]]

In [9]:
np_mat = np.array(mat)

In [10]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

## Zeros, Ones, Eye

In [12]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
np.eye(3) #Identity Matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Random

In [16]:
np.random.randn(5) #One dimensional

array([ 0.25987104,  0.9760972 ,  0.03172408,  0.36389394, -1.22826887])

In [17]:
np.random.randn(3,4) #Two dimensional

array([[ 0.7631006 ,  1.24706416, -0.28197328, -2.18472784],
       [-1.3788143 , -0.67960099,  0.16041042,  1.25985525],
       [-1.54851271,  0.82031827, -0.33947017, -0.54301553]])

In [18]:
np.random.randint(5, 15) #Random number between start and end

10

In [19]:
np.random.randint(5, 150, 5) #Multiple random numbers between specified range

array([134, 100,   7,  86,  99])

## arange, linspace

In [20]:
np.arange(3, 12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(3, 12, 2) #With a step of 2

array([ 3,  5,  7,  9, 11])

In [26]:
np.linspace(2, 5) #Default count is 50 -- Third argument

array([ 2.        ,  2.06122449,  2.12244898,  2.18367347,  2.24489796,
        2.30612245,  2.36734694,  2.42857143,  2.48979592,  2.55102041,
        2.6122449 ,  2.67346939,  2.73469388,  2.79591837,  2.85714286,
        2.91836735,  2.97959184,  3.04081633,  3.10204082,  3.16326531,
        3.2244898 ,  3.28571429,  3.34693878,  3.40816327,  3.46938776,
        3.53061224,  3.59183673,  3.65306122,  3.71428571,  3.7755102 ,
        3.83673469,  3.89795918,  3.95918367,  4.02040816,  4.08163265,
        4.14285714,  4.20408163,  4.26530612,  4.32653061,  4.3877551 ,
        4.44897959,  4.51020408,  4.57142857,  4.63265306,  4.69387755,
        4.75510204,  4.81632653,  4.87755102,  4.93877551,  5.        ])

In [27]:
np.linspace(2, 5, 10) #Third argument specifies the count of numbers

array([ 2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ])

## Operations

In [28]:
np_vec

array([1, 2, 3])

In [29]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

In [30]:
np_vec.shape #to find dimensions

(3,)

In [31]:
np_mat.shape

(2, 3)

In [32]:
np_vec.max() #Maximum value

3

In [33]:
np_vec.min() #Minimum value

1

In [34]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

In [36]:
np_mat.reshape(3, 2) #Change dimensions -- only if the total number of values remains the same

array([[2, 6],
       [8, 3],
       [7, 0]])

In [37]:
np_mat.reshape(3, 4) #Error since total number of elements changes

ValueError: cannot reshape array of size 6 into shape (3,4)

In [39]:
np_mat.dtype #to find Data Type of elements

dtype('int32')

# Numpy Array Operation

In [40]:
a = np.array([0, 1, 2, 3, 4, 5])

In [41]:
a + 7 #Add 7 to each element

array([ 7,  8,  9, 10, 11, 12])

In [42]:
a -2 

array([-2, -1,  0,  1,  2,  3])

In [43]:
a * 3

array([ 0,  3,  6,  9, 12, 15])

In [44]:
a / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5])

In [46]:
np.sin(a) #Calculate sin of each element

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [47]:
np.sum(a) #Sum of all values

15

In [48]:
np.mean(a) #Mean of all values

2.5

In [49]:
a1 = np.array([[1, 3], [4, 6]])
b1 = np.array([[0, 2], [3, 1]])

In [50]:
a1

array([[1, 3],
       [4, 6]])

In [51]:
b1

array([[0, 2],
       [3, 1]])

In [52]:
a1 + b1

array([[1, 5],
       [7, 7]])

In [53]:
a1 - b1

array([[1, 1],
       [1, 5]])

In [55]:
a1 * b1 #Element by element multiplication

array([[ 0,  6],
       [12,  6]])

In [56]:
a1.dot(b1) #Matrix Multiplication-- dot refers to matrix multiplication

array([[ 9,  5],
       [18, 14]])

In [57]:
a

array([0, 1, 2, 3, 4, 5])

In [58]:
a > 2 #Compare each and every element

array([False, False, False,  True,  True,  True], dtype=bool)

# Indexing, Slicing, Broadcasting

In [59]:
d1 = np.arange(25)

In [60]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
d2 = np.arange(25).reshape(5,5)

In [62]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
d1[4:12] #Slicing -- d1[start : end+1]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
d1[4: ]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [65]:
d1[:13]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
d2[0,0] #d2[row, column]

0

In [68]:
d2[2,]

array([10, 11, 12, 13, 14])

In [69]:
d2[1, :]

array([5, 6, 7, 8, 9])

In [70]:
d2[:, 3]

array([ 3,  8, 13, 18, 23])

In [72]:
d2[ , 4] #Error!

SyntaxError: invalid syntax (<ipython-input-72-5a4392cda82b>, line 1)

In [73]:
d2[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [74]:
d1[0:5]

array([0, 1, 2, 3, 4])

In [77]:
d1[0:5] = -10 #Broadcasting -- Change specific elements of the array

In [76]:
d1

array([-10, -10, -10, -10, -10,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])